/**
 * Circuit Storage, Export, Import, and Sharing Utilities
 * for Seeing Quantum Workbench
 */

const STORAGE_KEY = 'seeing_quantum_saved_circuits';
const DRAFT_KEY = 'seeing_quantum_current_draft';

// Default starter templates to inspire users
export const STARTER_TEMPLATES = [
  {
    id: 'template_bell_state',
    name: 'Bell State (|Φ+⟩)',
    description: 'Maximal entanglement between two qubits creating state (|00⟩ + |11⟩)/√2',
    isTemplate: true,
    gates: [
      { id: 't1', type: 'h', qubit: 0 },
      { id: 't2', type: 'cx', control: 0, target: 1 }
    ]
  },
  {
    id: 'template_superposition',
    name: 'Equal Superposition (H ⊗ H)',
    description: 'Applies Hadamard gates to all qubits creating state (|00⟩ + |01⟩ + |10⟩ + |11⟩)/2',
    isTemplate: true,
    gates: [
      { id: 't3', type: 'h', qubit: 0 },
      { id: 't4', type: 'h', qubit: 1 }
    ]
  },
  {
    id: 'template_swap',
    name: 'State Swap Circuit',
    description: 'Prepares |10⟩ state and swaps qubit 0 and 1 using SWAP gate',
    isTemplate: true,
    gates: [
      { id: 't5', type: 'x', qubit: 0 },
      { id: 't6', type: 'swap', control: 0, target: 1 }
    ]
  }
];

// --- Local Storage Management ---

export function getSavedCircuits() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('Failed to load saved circuits from localStorage:', err);
    return [];
  }
}

export function saveCircuitToLocal({ id, name, description, gates }) {
  try {
    const existing = getSavedCircuits();
    const now = new Date().toISOString();
    const cleanGates = sanitizeGates(gates);

    const circuitId = id && !id.startsWith('template_') ? id : `circ_${Date.now()}`;
    const cleanName = (name && name.trim()) || `Circuit ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;

    const newRecord = {
      id: circuitId,
      name: cleanName,
      description: description ? description.trim() : '',
      gates: cleanGates,
      createdAt: now,
      updatedAt: now
    };

    const index = existing.findIndex(c => c.id === circuitId);
    let updated;
    if (index >= 0) {
      newRecord.createdAt = existing[index].createdAt || now;
      updated = [...existing];
      updated[index] = newRecord;
    } else {
      updated = [newRecord, ...existing];
    }

    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    return newRecord;
  } catch (err) {
    console.error('Failed to save circuit to localStorage:', err);
    throw err;
  }
}

export function deleteSavedCircuit(id) {
  try {
    const existing = getSavedCircuits();
    const updated = existing.filter(c => c.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    return updated;
  } catch (err) {
    console.error('Failed to delete circuit from localStorage:', err);
    throw err;
  }
}

export function saveDraft(gates, name = '') {
  try {
    localStorage.setItem(DRAFT_KEY, JSON.stringify({
      gates: sanitizeGates(gates),
      name,
      savedAt: Date.now()
    }));
  } catch (e) {
    // Ignore storage errors on draft
  }
}

export function loadDraft() {
  try {
    const raw = localStorage.getItem(DRAFT_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch (e) {
    return null;
  }
}

// --- Sanitization & Normalization ---

export function sanitizeGates(gates) {
  if (!Array.isArray(gates)) return [];
  return gates.map((g, idx) => {
    const type = (g.type || '').toLowerCase();
    if (type === 'cx' || type === 'swap') {
      return {
        id: g.id || `gate_${idx}_${Date.now()}`,
        type,
        control: Number.isInteger(g.control) ? g.control : 0,
        target: Number.isInteger(g.target) ? g.target : 1
      };
    } else {
      return {
        id: g.id || `gate_${idx}_${Date.now()}`,
        type,
        qubit: Number.isInteger(g.qubit) ? g.qubit : 0
      };
    }
  });
}

// --- Code Generators for Export ---

export function generateQiskitCode(circuitName, gates) {
  const cleanGates = sanitizeGates(gates);
  let code = `"""\nQuantum Circuit: ${circuitName || 'Seeing Quantum Circuit'}\nGenerated by Seeing Quantum\n"""\n\n`;
  code += `from qiskit import QuantumCircuit, transpile\n`;
  code += `from qiskit_aer import AerSimulator\n\n`;
  code += `# Initialize a 2-qubit circuit with 2 classical registers\n`;
  code += `qc = QuantumCircuit(2, 2)\n\n`;

  if (cleanGates.length === 0) {
    code += `# (No gates placed)\n`;
  } else {
    code += `# Apply quantum logic gates\n`;
    cleanGates.forEach(g => {
      if (g.type === 'cx' || g.type === 'swap') {
        code += `qc.${g.type}(${g.control}, ${g.target})\n`;
      } else {
        code += `qc.${g.type}(${g.qubit})\n`;
      }
    });
  }

  code += `\n# Measurement of qubits onto classical register\n`;
  code += `qc.measure([0, 1], [0, 1])\n\n`;
  code += `# Simulate circuit with Aer simulator\n`;
  code += `simulator = AerSimulator()\n`;
  code += `compiled_circuit = transpile(qc, simulator)\n`;
  code += `job = simulator.run(compiled_circuit, shots=1024)\n`;
  code += `result = job.result()\n`;
  code += `counts = result.get_counts(qc)\n`;
  code += `print("Measurement counts:", counts)\n`;

  return code;
}

export function generateQASMCode(circuitName, gates) {
  const cleanGates = sanitizeGates(gates);
  let qasm = `// Circuit: ${circuitName || 'Seeing Quantum Circuit'}\n`;
  qasm += `// Generated by Seeing Quantum\n`;
  qasm += `OPENQASM 2.0;\n`;
  qasm += `include "qelib1.inc";\n\n`;
  qasm += `qreg q[2];\n`;
  qasm += `creg c[2];\n\n`;

  cleanGates.forEach(g => {
    if (g.type === 'cx') {
      qasm += `cx q[${g.control}], q[${g.target}];\n`;
    } else if (g.type === 'swap') {
      // OpenQASM SWAP is either swap q0, q1 or 3 CXs
      qasm += `swap q[${g.control}], q[${g.target}];\n`;
    } else {
      qasm += `${g.type} q[${g.qubit}];\n`;
    }
  });

  qasm += `\nmeasure q[0] -> c[0];\n`;
  qasm += `measure q[1] -> c[1];\n`;

  return qasm;
}

// --- Download Helpers ---

function triggerDownload(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function sanitizeFilename(name) {
  return (name || 'quantum-circuit')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'quantum-circuit';
}

export function exportCircuitAsJSON(circuitName, gates) {
  const data = {
    schemaVersion: 1,
    app: 'Seeing Quantum',
    exportedAt: new Date().toISOString(),
    circuit: {
      name: circuitName || 'Untitled Circuit',
      numQubits: 2,
      gates: sanitizeGates(gates)
    }
  };
  const jsonStr = JSON.stringify(data, null, 2);
  const filename = `${sanitizeFilename(circuitName)}.json`;
  triggerDownload(jsonStr, filename, 'application/json');
}

export function exportCircuitAsPython(circuitName, gates) {
  const code = generateQiskitCode(circuitName, gates);
  const filename = `${sanitizeFilename(circuitName)}.py`;
  triggerDownload(code, filename, 'text/x-python');
}

export function exportCircuitAsQASM(circuitName, gates) {
  const qasm = generateQASMCode(circuitName, gates);
  const filename = `${sanitizeFilename(circuitName)}.qasm`;
  triggerDownload(qasm, filename, 'text/plain');
}

// --- Import Helper ---

export function parseImportedJSON(text) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    throw new Error('Invalid JSON file format.');
  }

  let gates = [];
  let name = 'Imported Circuit';

  if (parsed.circuit && Array.isArray(parsed.circuit.gates)) {
    gates = parsed.circuit.gates;
    name = parsed.circuit.name || name;
  } else if (Array.isArray(parsed.gates)) {
    gates = parsed.gates;
    name = parsed.name || name;
  } else if (Array.isArray(parsed)) {
    gates = parsed;
  } else {
    throw new Error('JSON does not contain recognized quantum circuit gate data.');
  }

  return {
    name,
    gates: sanitizeGates(gates)
  };
}

// --- URL Sharing (Compact base64 encoding) ---

/**
 * Compact format:
 * {
 *   n: name,
 *   g: [ ['h', 0], ['cx', 0, 1] ]
 * }
 */
export function encodeCircuitPayload(name, gates) {
  const cleanGates = sanitizeGates(gates);
  const compact = {
    n: name || 'Quantum Circuit',
    g: cleanGates.map(g => {
      if (g.type === 'cx' || g.type === 'swap') {
        return [g.type, g.control, g.target];
      }
      return [g.type, g.qubit];
    })
  };

  const jsonStr = JSON.stringify(compact);
  // URL-safe base64: replace '+' with '-', '/' with '_', and strip '='
  const utf8Bytes = encodeURIComponent(jsonStr).replace(/%([0-9A-F]{2})/g, (_, p1) => {
    return String.fromCharCode(parseInt(p1, 16));
  });
  const b64 = btoa(utf8Bytes)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
  return b64;
}

export function decodeCircuitPayload(encodedStr) {
  if (!encodedStr) return null;
  try {
    // Restore base64 padding and chars
    let b64 = encodedStr.replace(/-/g, '+').replace(/_/g, '/');
    while (b64.length % 4) {
      b64 += '=';
    }
    const binary = atob(b64);
    const jsonStr = decodeURIComponent(
      Array.prototype.map.call(binary, c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)).join('')
    );
    const parsed = JSON.parse(jsonStr);

    const name = parsed.n || 'Shared Circuit';
    const gates = [];
    let idCounter = 1;

    if (Array.isArray(parsed.g)) {
      parsed.g.forEach(item => {
        if (!Array.isArray(item) || item.length < 2) return;
        const type = String(item[0]).toLowerCase();
        if ((type === 'cx' || type === 'swap') && item.length >= 3) {
          gates.push({
            id: `shared_${idCounter++}`,
            type,
            control: Number(item[1]),
            target: Number(item[2])
          });
        } else {
          gates.push({
            id: `shared_${idCounter++}`,
            type,
            qubit: Number(item[1])
          });
        }
      });
    }

    return { name, gates };
  } catch (err) {
    console.error('Failed to decode circuit from URL:', err);
    return null;
  }
}

/**
 * Builds the full shareable link with access mode ('readonly' or 'write')
 */
export function buildShareLink(name, gates, accessMode = 'readonly') {
  const payload = encodeCircuitPayload(name, gates);
  const url = new URL(window.location.origin + window.location.pathname);
  url.searchParams.set('page', 'workbench');
  url.searchParams.set('circuit', payload);
  url.searchParams.set('access', accessMode === 'write' ? 'write' : 'readonly');
  return url.toString();
}

/**
 * Checks URL query params (and hash) for any shared circuit configuration
 */
export function getSharedCircuitFromUrl() {
  try {
    let params = new URLSearchParams(window.location.search);
    let circuitParam = params.get('circuit');
    let accessParam = params.get('access') || 'readonly';

    // Also check hash fragment if query params were empty (e.g., #circuit=...&access=...)
    if (!circuitParam && window.location.hash) {
      const hashStr = window.location.hash.replace(/^#/, '');
      const hashParams = new URLSearchParams(hashStr);
      circuitParam = hashParams.get('circuit');
      if (hashParams.get('access')) {
        accessParam = hashParams.get('access');
      }
    }

    if (!circuitParam) return null;

    const decoded = decodeCircuitPayload(circuitParam);
    if (!decoded) return null;

    return {
      circuit: decoded,
      accessMode: accessParam === 'write' ? 'write' : 'readonly'
    };
  } catch (e) {
    console.error('Error parsing shared circuit from URL:', e);
    return null;
  }
}

/**
 * Safe clipboard copy with fallback
 */
export async function copyTextToClipboard(text) {
  if (navigator?.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (e) {
      // Fall through to fallback
    }
  }

  try {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textArea);
    return success;
  } catch (err) {
    console.error('Fallback clipboard copy failed:', err);
    return false;
  }
}
